### ISSUE TITLE
Optional header vs footer?

### ISSUE THREAD

**Issue by rjzak** [CybercentreCanada/cart-rs#4]
I'm trying to add metadata to the CaRT file, including different hashes. If I don't add an optional header or footer, my test with `assert!(cart::cart::unpack_stream(bytes_input, output, None).is_ok());` passes, but adding a header or footer gives an `Could not unpack header` error.

Example of creating the header:

```rust
let mut output_metadata = cart::cart::JsonMap::new();
output_metadata["md5"] = report.md5.parse()?; // String parsed to `serde_json::Value`
output_metadata["sha1"] = report.sha1.parse()?;
output_metadata["sha256"] = report.sha256.parse()?;
output_metadata["sha384"] = report.sha384.parse()?;
output_metadata["sha512"] = report.sha512.parse()?;
output_metadata["entropy"] = serde_json::Value::from(report.entropy); // `f32`
if let Some(filecmd) = report.filecommand {
    output_metadata["file"] = filecmd.parse()?;
}

cart::cart::pack_stream(
    contents_cursor, // Cursor wrapping the vec of data
    &mut output_cursor, // Cursor wrapping empty vec
    None, // Optional header, tried this for the metadata
    Some(output_metadata), // Optional footer
    cart::digesters::default_digesters(),
    None, // Rc4 key override, not used
)?;
```

This compiles and executes fine, but decoding causes an error. I'm also not messing with the Rc4 key, leaving that value as `None`.

**Comment by cccs-douglass** [comment]
I'm trying to track down the issue you're having but you'll have to help me get there. I'm guessing right now that it has to do with some interaction caused by setting a footer and digest functions.

I can't get the code you've shared to work. I assume this is a minimal snippet of something larger. 
1. IIRC parse on a string to json Value actually parses the string as json. Using into/from or the serde_json::json! macro should do what you really need. 
2. Again IIRC, the [] syntax on a map will only let you access/modify entries that already exist in the map.

The header is usually used for "user metadata" and hashes are typically stored in the footer. The digesters is a list of digests to add to the footer. Some of this is covered in the upstream repo for the format https://github.com/CybercentreCanada/cart, but some just should be documented better.

So far this is my test case for this but its passing:
```rust
#[test]
fn conflicting_footer_data() {
    let raw_data = std::include_bytes!("cart.rs");
    let mut output = vec![];

    let mut output_metadata = super::JsonMap::new();
    output_metadata.insert("md5".to_owned(), "report.md5".into()); // String intod )o `serde_json::Value`
    output_metadata.insert("sha1".to_owned(), "report.sha1".into());
    output_metadata.insert("sha256".to_owned(), "report.sha256".into());
    output_metadata.insert("sha384".to_owned(), "report.sha384".into());
    output_metadata.insert("sha512".to_owned(), "report.sha512".into());
    output_metadata.insert("entropy".to_owned(), serde_json::Value::from(5.0f32)); // `f32`
    output_metadata.insert("file".to_owned(), "filecmd".into());

    pack_stream(
        std::io::Cursor::new(raw_data), // Cursor wrapping the vec of data
        &mut output, // Cursor wrapping empty vec
        None, // Optional header, tried this for the metadata
        Some(output_metadata), // Optional footer
        default_digesters(),
        None, // Rc4 key override, not used
    ).unwrap();

    let mut unpacked = vec![];

    let (header, footer) = unpack_stream(std::io::Cursor::new(output), &mut unpacked, None).unwrap();

    assert!(header.is_none()); // nothing should be added
    assert_eq!(unpacked, raw_data); // data should be preserved
    let footer = footer.unwrap(); // there must be a footer
    assert_ne!(footer["md5"], "report.md5"); // this should be overwritten with the real md5
    assert_eq!(footer["entropy"], serde_json::json!(5.0)); // this won't be effected by the digester
}
```

**Comment by rjzak** [comment]
That did it! I wasn't used the JsonMap correctly. Thank you!
